// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjW_3ZOgGoMArbH_0J_eJaAbdfG_4oyCI',
    appId: '1:870604795414:web:11d80eb13669d1d446cf37',
    messagingSenderId: '870604795414',
    projectId: 'tp-shop-flutter',
    authDomain: 'tp-shop-flutter.firebaseapp.com',
    storageBucket: 'tp-shop-flutter.firebasestorage.app',
    measurementId: 'G-KH4N488YB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwxGaSyiwQDFlhZmRmD3pphLDFW0aEQUs',
    appId: '1:870604795414:android:10f4967cb3ef109f46cf37',
    messagingSenderId: '870604795414',
    projectId: 'tp-shop-flutter',
    storageBucket: 'tp-shop-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe_ICc_GH31Nci_F3KyMzdoNuXVuh-yZo',
    appId: '1:870604795414:ios:2c257d51a51715d546cf37',
    messagingSenderId: '870604795414',
    projectId: 'tp-shop-flutter',
    storageBucket: 'tp-shop-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe_ICc_GH31Nci_F3KyMzdoNuXVuh-yZo',
    appId: '1:870604795414:ios:2c257d51a51715d546cf37',
    messagingSenderId: '870604795414',
    projectId: 'tp-shop-flutter',
    storageBucket: 'tp-shop-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjW_3ZOgGoMArbH_0J_eJaAbdfG_4oyCI',
    appId: '1:870604795414:web:b613362ed622b45946cf37',
    messagingSenderId: '870604795414',
    projectId: 'tp-shop-flutter',
    authDomain: 'tp-shop-flutter.firebaseapp.com',
    storageBucket: 'tp-shop-flutter.firebasestorage.app',
    measurementId: 'G-NDHMJCVY98',
  );
}
